

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WishList](
	[WishListID] [bigint] IDENTITY(1,1) NOT NULL,
	[CustomerID] [nvarchar](100) NULL,
	[BookID] [bigint] NULL,
 CONSTRAINT [WishListID_PK] PRIMARY KEY CLUSTERED 
(
	[WishListID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WishList]  WITH CHECK ADD  CONSTRAINT [WishList_BookID_FK] FOREIGN KEY([BookID])
REFERENCES [dbo].[Book] ([BookID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[WishList] CHECK CONSTRAINT [WishList_BookID_FK]
GO
ALTER TABLE [dbo].[WishList]  WITH CHECK ADD  CONSTRAINT [WishList_CustomerID_FK] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customer] ([CustomerID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[WishList] CHECK CONSTRAINT [WishList_CustomerID_FK]
GO
